// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/mytheresa/go-hiring-challenge/app/domain"
)

// MockGetCatalogByCode is a mock of GetCatalogByCode interface.
type MockGetCatalogByCode struct {
	ctrl     *gomock.Controller
	recorder *MockGetCatalogByCodeMockRecorder
}

// MockGetCatalogByCodeMockRecorder is the mock recorder for MockGetCatalogByCode.
type MockGetCatalogByCodeMockRecorder struct {
	mock *MockGetCatalogByCode
}

// NewMockGetCatalogByCode creates a new mock instance.
func NewMockGetCatalogByCode(ctrl *gomock.Controller) *MockGetCatalogByCode {
	mock := &MockGetCatalogByCode{ctrl: ctrl}
	mock.recorder = &MockGetCatalogByCodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetCatalogByCode) EXPECT() *MockGetCatalogByCodeMockRecorder {
	return m.recorder
}

// GetByCode mocks base method.
func (m *MockGetCatalogByCode) GetByCode(code string) (*domain.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", code)
	ret0, _ := ret[0].(*domain.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockGetCatalogByCodeMockRecorder) GetByCode(code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockGetCatalogByCode)(nil).GetByCode), code)
}

// MockResponder is a mock of Responder interface.
type MockResponder struct {
	ctrl     *gomock.Controller
	recorder *MockResponderMockRecorder
}

// MockResponderMockRecorder is the mock recorder for MockResponder.
type MockResponderMockRecorder struct {
	mock *MockResponder
}

// NewMockResponder creates a new mock instance.
func NewMockResponder(ctrl *gomock.Controller) *MockResponder {
	mock := &MockResponder{ctrl: ctrl}
	mock.recorder = &MockResponderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponder) EXPECT() *MockResponderMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockResponder) Error(w http.ResponseWriter, status int, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", w, status, message)
}

// Error indicates an expected call of Error.
func (mr *MockResponderMockRecorder) Error(w, status, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockResponder)(nil).Error), w, status, message)
}

// Ok mocks base method.
func (m *MockResponder) Ok(w http.ResponseWriter, data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ok", w, data)
}

// Ok indicates an expected call of Ok.
func (mr *MockResponderMockRecorder) Ok(w, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ok", reflect.TypeOf((*MockResponder)(nil).Ok), w, data)
}
