// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/mytheresa/go-hiring-challenge/app/domain"
)

// MockCategoriesCreator is a mock of CategoriesCreator interface.
type MockCategoriesCreator struct {
	ctrl     *gomock.Controller
	recorder *MockCategoriesCreatorMockRecorder
}

// MockCategoriesCreatorMockRecorder is the mock recorder for MockCategoriesCreator.
type MockCategoriesCreatorMockRecorder struct {
	mock *MockCategoriesCreator
}

// NewMockCategoriesCreator creates a new mock instance.
func NewMockCategoriesCreator(ctrl *gomock.Controller) *MockCategoriesCreator {
	mock := &MockCategoriesCreator{ctrl: ctrl}
	mock.recorder = &MockCategoriesCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoriesCreator) EXPECT() *MockCategoriesCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoriesCreator) Create(req *domain.CreateCategoryRequest) (*domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(*domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCategoriesCreatorMockRecorder) Create(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoriesCreator)(nil).Create), req)
}

// MockResponder is a mock of Responder interface.
type MockResponder struct {
	ctrl     *gomock.Controller
	recorder *MockResponderMockRecorder
}

// MockResponderMockRecorder is the mock recorder for MockResponder.
type MockResponderMockRecorder struct {
	mock *MockResponder
}

// NewMockResponder creates a new mock instance.
func NewMockResponder(ctrl *gomock.Controller) *MockResponder {
	mock := &MockResponder{ctrl: ctrl}
	mock.recorder = &MockResponderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponder) EXPECT() *MockResponderMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockResponder) Error(w http.ResponseWriter, status int, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", w, status, message)
}

// Error indicates an expected call of Error.
func (mr *MockResponderMockRecorder) Error(w, status, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockResponder)(nil).Error), w, status, message)
}

// Ok mocks base method.
func (m *MockResponder) Ok(w http.ResponseWriter, data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ok", w, data)
}

// Ok indicates an expected call of Ok.
func (mr *MockResponderMockRecorder) Ok(w, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ok", reflect.TypeOf((*MockResponder)(nil).Ok), w, data)
}
